#!/usr/bin/env python3
"""Sync the site owner's public GitHub data into _data/github/*.yml.

Used by .github/workflows/sync-github.yml (daily) and runnable locally.
Auth: GH_TOKEN env (Actions: secrets.GITHUB_TOKEN; local: `gh auth token`).
User: GH_USER env (default: bamr87).

Writes six files consumed at build time via site.data.github.*:
  profile.yml pinned.yml repos.yml starred.yml languages.yml activity.yml
Network/permission failures degrade gracefully: existing files are left intact
(or valid empty stubs written) so the Jekyll build always stays green.
"""
import os
import sys
import datetime
import json
import urllib.request
import urllib.error

try:
    import yaml
except ImportError:
    print("pyyaml required: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

USER = os.environ.get("GH_USER", "bamr87")
TOKEN = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN")
OUT = os.path.join(os.path.dirname(__file__), "..", "..", "_data", "github")
NOW = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _req(url, data=None, graphql=False):
    headers = {"Accept": "application/vnd.github+json", "User-Agent": "it-journey-sync"}
    if TOKEN:
        headers["Authorization"] = "Bearer " + TOKEN
    body = None
    if graphql:
        body = json.dumps({"query": data}).encode()
        headers["Content-Type"] = "application/json"
    req = urllib.request.Request(url, data=body, headers=headers, method="POST" if graphql else "GET")
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read().decode())


def rest(path):
    return _req("https://api.github.com" + path)


def graphql(query):
    return _req("https://api.github.com/graphql", data=query, graphql=True)


def write(name, obj):
    os.makedirs(OUT, exist_ok=True)
    path = os.path.join(OUT, name + ".yml")
    obj = {"generated_at": NOW, **obj}
    with open(path, "w") as f:
        f.write("# Auto-generated by scripts/generation/sync_github.py — do not edit.\n")
        yaml.safe_dump(obj, f, sort_keys=False, allow_unicode=True, default_flow_style=False)
    print("wrote", path)


def repo_obj(r):
    lang = r.get("language")
    return {
        "name": r.get("name"),
        "description": r.get("description") or "",
        "url": r.get("html_url"),
        "homepage": r.get("homepage") or "",
        "stars": r.get("stargazers_count", 0),
        "forks": r.get("forks_count", 0),
        "language": lang or "",
        "pushed_at": r.get("pushed_at"),
        "topics": (r.get("topics") or [])[:5],
    }


def main():
    # ---- profile ----
    try:
        p = rest("/users/" + USER)
        gq = graphql('{user(login:"%s"){starredRepositories{totalCount} repositories(ownerAffiliations:OWNER){totalCount}}}' % USER)
        gu = (gq.get("data") or {}).get("user") or {}
        write("profile", {
            "login": p.get("login"), "name": p.get("name") or p.get("login"),
            "avatar_url": p.get("avatar_url"), "bio": p.get("bio") or "",
            "company": p.get("company") or "", "location": p.get("location") or "",
            "blog": p.get("blog") or "", "html_url": p.get("html_url"),
            "hireable": p.get("hireable"), "followers": p.get("followers", 0),
            "following": p.get("following", 0), "public_repos": p.get("public_repos", 0),
            "member_since": (p.get("created_at") or "")[:10],
            "totals": {
                "owned_repos": (gu.get("repositories") or {}).get("totalCount", p.get("public_repos", 0)),
                "starred": (gu.get("starredRepositories") or {}).get("totalCount", 0),
            },
        })
    except Exception as e:
        print("profile sync failed:", e, file=sys.stderr)

    # ---- repos (recent + top by stars) + languages ----
    try:
        repos = rest("/users/%s/repos?sort=pushed&direction=desc&per_page=100&type=owner" % USER)
        repos = [r for r in repos if not r.get("fork")]
        objs = [repo_obj(r) for r in repos]
        recent = objs[:8]
        top = sorted(objs, key=lambda x: -x["stars"])[:8]
        write("repos", {"recent": recent, "top_starred": top})
        # languages tally
        tally = {}
        for r in objs:
            if r["language"]:
                tally[r["language"]] = tally.get(r["language"], 0) + 1
        ranked = [{"name": k, "repos": v} for k, v in sorted(tally.items(), key=lambda kv: -kv[1])][:8]
        write("languages", {"ranked": ranked})
    except Exception as e:
        print("repos sync failed:", e, file=sys.stderr)

    # ---- pinned (GraphQL) ----
    try:
        q = ('{user(login:"%s"){pinnedItems(first:6,types:REPOSITORY){nodes{'
             '...on Repository{name description url stargazerCount forkCount '
             'primaryLanguage{name color}}}}}}' % USER)
        nodes = ((graphql(q).get("data") or {}).get("user") or {}).get("pinnedItems", {}).get("nodes", [])
        items = [{
            "name": n.get("name"), "description": n.get("description") or "",
            "url": n.get("url"), "stars": n.get("stargazerCount", 0), "forks": n.get("forkCount", 0),
            "language": (n.get("primaryLanguage") or {}).get("name", ""),
            "language_color": (n.get("primaryLanguage") or {}).get("color", ""),
        } for n in nodes if n]
        write("pinned", {"items": items})
    except Exception as e:
        print("pinned sync failed:", e, file=sys.stderr)

    # ---- starred ----
    try:
        s = rest("/users/%s/starred?per_page=12&sort=created" % USER)
        items = [{
            "full_name": r.get("full_name"), "url": r.get("html_url"),
            "description": r.get("description") or "", "stars": r.get("stargazers_count", 0),
            "language": r.get("language") or "",
        } for r in s]
        write("starred", {"items": items})
    except Exception as e:
        print("starred sync failed:", e, file=sys.stderr)

    # ---- activity (contribution calendar) ----
    try:
        q = ('{user(login:"%s"){contributionsCollection{contributionCalendar{'
             'totalContributions weeks{contributionDays{date contributionCount}}}}}}' % USER)
        cc = (((graphql(q).get("data") or {}).get("user") or {})
              .get("contributionsCollection") or {}).get("contributionCalendar") or {}
        days = []
        for wk in cc.get("weeks", []):
            for d in wk.get("contributionDays", []):
                days.append({"date": d["date"], "count": d["contributionCount"]})
        write("activity", {"total_contributions": cc.get("totalContributions", 0), "days": days})
    except Exception as e:
        print("activity sync failed:", e, file=sys.stderr)


if __name__ == "__main__":
    main()
