#!/usr/bin/env bash
# generate-network-report.sh
# Generates a summary of quest network connections

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
print_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
print_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
print_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
QUEST_DIR="${PROJECT_ROOT}/pages/_quests"
REPORT_FILE="${QUEST_DIR}/NETWORK_REPORT.md"

# Function to display usage
usage() {
    cat <<EOF
Usage: $0 [options]

Generate a summary report of quest network connections.

Options:
    -o, --output FILE    Output file path (default: pages/_quests/NETWORK_REPORT.md)
    -h, --help           Show this help message

Examples:
    $0                    # Generate report to default location
    $0 -o custom-report.md # Generate report to custom file

EOF
    exit 1
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        -o|--output)
            REPORT_FILE="$2"
            shift 2
            ;;
        -h|--help)
            usage
            ;;
        *)
            print_error "Unknown option: $1"
            usage
            ;;
    esac
done

if [[ ! -d "$QUEST_DIR" ]]; then
    print_error "Quest directory not found: $QUEST_DIR"
    exit 1
fi

print_info "Generating quest network report..."
print_info "Quest directory: $QUEST_DIR"
print_info "Output file: $REPORT_FILE"
echo ""

# Run validation script and capture output
VALIDATOR_SCRIPT="${SCRIPT_DIR}/validate-quest-network.py"

if [[ ! -f "$VALIDATOR_SCRIPT" ]]; then
    print_error "Validator script not found: $VALIDATOR_SCRIPT"
    exit 1
fi

# Generate report header
cat > "$REPORT_FILE" <<EOF
# Quest Network Report

**Generated:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")
**Quest Directory:** \`$QUEST_DIR\`

---

## Validation Summary

EOF

# Run validator and append results
print_info "Running quest network validator..."
if python3 "$VALIDATOR_SCRIPT" >> "$REPORT_FILE" 2>&1; then
    print_success "Validation completed"
else
    print_warning "Validation completed with errors (see report)"
fi

# Append additional analysis
cat >> "$REPORT_FILE" <<EOF

---

## Report Generation

This report was generated by running:
\`\`\`bash
python3 scripts/quest/validate-quest-network.py
\`\`\`

For more details, see:
- [QUEST_BUILD_PLAN.md](QUEST_BUILD_PLAN.md)
- [docs/PHASE6_PLAN.md](docs/PHASE6_PLAN.md)

EOF

print_success "Report generated: $REPORT_FILE"
print_info "View the report with: cat $REPORT_FILE"
