#!/usr/bin/env python3
"""Emit ``_data/quests/levels.yml`` from ``scripts/quest/quest_registry.py``.

The generated file is consumed by quest layouts and includes so they can
render tier names, themes, and XP ranges without hardcoding strings.

Schema::

    levels:
      "0000":
        theme: "Foundation & Init World"
        tier: Apprentice
        decimal: 0
        xp_range: "0-250"
        permalink: /quests/0000/
        tier_emoji: 🌱
      "0001": {...}
    tiers:
      Apprentice:
        emoji: 🌱
        levels: ["0000", "0001", "0010", "0011"]
      ...
    order: ["0000", "0001", ..., "1111"]

Usage::

    python3 scripts/quest/generate-quest-levels-data.py [--dry-run]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    print("Error: PyYAML required", file=sys.stderr)
    sys.exit(1)

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))
from quest_registry import (  # noqa: E402
    LEVELS,
    LEVEL_ORDER,
    TIERS,
    TIER_EMOJI,
    canonical_level_permalink,
)

REPO_ROOT = SCRIPT_DIR.parent.parent
DATA_DIR = REPO_ROOT / "_data" / "quests"

# Emitted as THREE files so each file's content sits directly under
# ``site.data.quests.<name>`` (Jekyll keys data by file path). That gives the
# natural, shallow accessors templates use:
#     site.data.quests.levels[code]   site.data.quests.tiers[name]   site.data.quests.order
OUT = {
    "levels.yml": "levels",
    "tiers.yml": "tiers",
    "order.yml": "order",
}

HEADER = (
    "# Auto-generated by scripts/quest/generate-quest-levels-data.py — do not edit.\n"
    "# Run `make quest-levels-data` to refresh from scripts/quest/quest_registry.py.\n"
)


def build_payloads() -> dict:
    levels = {}
    for code in LEVEL_ORDER:
        meta = LEVELS[code]
        levels[code] = {
            "theme": meta["theme"],
            "tier": meta["tier"],
            "decimal": meta["decimal"],
            "xp_range": meta["xp_range"],
            "permalink": canonical_level_permalink(code),
            "tier_emoji": TIER_EMOJI[meta["tier"]],
            "icon": meta["icon"],
        }

    tiers = {
        name: {"emoji": TIER_EMOJI[name], "levels": codes}
        for name, codes in TIERS.items()
    }

    return {"levels": levels, "tiers": tiers, "order": list(LEVEL_ORDER)}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true", help="print without writing")
    args = parser.parse_args()

    payloads = build_payloads()

    if args.dry_run:
        for fname, key in OUT.items():
            print(f"# === {fname} ===")
            print(HEADER + yaml.dump(payloads[key], default_flow_style=False, allow_unicode=True, sort_keys=False))
        return 0

    DATA_DIR.mkdir(parents=True, exist_ok=True)
    for fname, key in OUT.items():
        body = HEADER + yaml.dump(payloads[key], default_flow_style=False, allow_unicode=True, sort_keys=False)
        (DATA_DIR / fname).write_text(body, encoding="utf-8")
    print(f"Wrote _data/quests/{{{', '.join(OUT)}}} "
          f"({len(payloads['levels'])} levels, {len(payloads['tiers'])} tiers)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
