#!/usr/bin/env bash
# =============================================================================
# refresh_report_branch.sh — bring a quest-perfection report branch back in sync
# -----------------------------------------------------------------------------
# The report lane's PR carries THREE kinds of file:
#
#   inputs   test/quest-validator/walkthroughs/<date>-<slice>.md   append-only,
#            date-named, so two runs never touch the same one — these never conflict
#   state    .quests/ledger.json                                    an accumulated
#            JSON document rewritten wholesale by every run
#   derived  .quests/DASHBOARD.md, pages/_quest-reports/**          regenerated
#            wholesale from (inputs + state) by every run
#
# So the moment a later run's PR merges to main, an earlier still-open report PR
# is guaranteed to conflict — not over anything a human decided, but over
# regenerated bytes. Git cannot line-merge them; the generators can.
#
# This merges the base branch in and then rebuilds the state + derived files from
# scratch, exactly the way the loop builds them:
#
#   1. structurally merge the two ledgers   (ledger.py merge — newer slice record
#      wins wholesale, walk history unions, circuit breaker only tightens)
#   2. re-render the ledger dashboard       (ledger.py render)
#   3. regenerate the Jekyll collection     (build_reports_site.py)
#
# It REFUSES to resolve anything outside that generated set: if the merge
# conflicts in quest content, a workflow, or a walkthrough source, it stops and
# leaves the tree for a human. Deterministic, no model, no network beyond fetch.
#
# Usage:
#   scripts/quest/refresh_report_branch.sh [base-ref]      # default: origin/main
#
# Exit codes: 0 refreshed (or already up to date) · 2 conflicts a human must take
# =============================================================================
set -euo pipefail

BASE="${1:-origin/main}"
REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

LEDGER=".quests/ledger.json"
DASHBOARD=".quests/DASHBOARD.md"
REPORTS="pages/_quest-reports"
WALKTHROUGHS="test/quest-validator/walkthroughs"

# Paths this script is allowed to resolve — everything here is regenerated below,
# so "resolving" means "rebuild it", never "pick a side and hope".
is_generated() {
  case "$1" in
    "$LEDGER"|"$DASHBOARD"|"$REPORTS"/*) return 0 ;;
    *) return 1 ;;
  esac
}

# Only the paths this script rewrites have to be clean; unrelated local edits
# (tooling you are testing, a scratch file) are none of its business, and it
# never stages them — the commit below is path-scoped.
if ! git diff --quiet -- "$LEDGER" "$DASHBOARD" "$REPORTS" "$WALKTHROUGHS" ||
   ! git diff --cached --quiet -- "$LEDGER" "$DASHBOARD" "$REPORTS" "$WALKTHROUGHS"; then
  echo "::error::uncommitted changes in the report/ledger paths — commit or stash them first." >&2
  exit 2
fi

if git merge-base --is-ancestor "$BASE" HEAD; then
  echo "Already up to date with $BASE — nothing to refresh."
  exit 0
fi

# Snapshot both ledgers BEFORE the merge can rewrite either one, so the
# structured merge below is a pure function of the two committed states (and is
# identical whether git's textual merge succeeded or conflicted).
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
git show "HEAD:$LEDGER"  > "$TMP/ours.json"   2>/dev/null || echo '{}' > "$TMP/ours.json"
git show "$BASE:$LEDGER" > "$TMP/theirs.json" 2>/dev/null || echo '{}' > "$TMP/theirs.json"

echo "▶ merging $BASE into $(git rev-parse --abbrev-ref HEAD)…"
if git merge --no-commit --no-ff "$BASE"; then
  echo "  clean merge."
else
  conflicts="$(git diff --name-only --diff-filter=U)"
  blocked=""
  while IFS= read -r f; do
    [ -n "$f" ] || continue
    is_generated "$f" || blocked="$blocked  $f"$'\n'
  done <<< "$conflicts"
  if [ -n "$blocked" ]; then
    echo "::error::conflicts outside the generated set — a human must resolve these:" >&2
    printf '%s' "$blocked" >&2
    echo "  (the tree is left mid-merge; 'git merge --abort' to back out)" >&2
    exit 2
  fi
  echo "  conflicts confined to generated files — rebuilding them:"
  printf '%s\n' "$conflicts" | sed 's/^/    /'
  # Take the base's side verbatim for the derived pages. They are overwritten
  # wholesale in step 3; this only clears the conflict markers first so the
  # generator can read the base's PUBLISHED run URLs (which it pins — see
  # run_url_for) instead of parsing a half-merged file.
  while IFS= read -r f; do
    [ -n "$f" ] || continue
    git checkout --theirs -- "$f" 2>/dev/null || git checkout "$BASE" -- "$f"
    git add -- "$f"
  done <<< "$conflicts"
fi

echo "▶ 1/3 merging the ledger structurally…"
python3 scripts/quest/ledger.py merge \
  --ours "$TMP/ours.json" --theirs "$TMP/theirs.json" --output "$LEDGER"

echo "▶ 2/3 re-rendering $DASHBOARD…"
python3 scripts/quest/ledger.py render

echo "▶ 3/3 regenerating $REPORTS from $WALKTHROUGHS + the ledger…"
python3 scripts/quest/build_reports_site.py

git add -- "$LEDGER" "$DASHBOARD" "$REPORTS" "$WALKTHROUGHS"

# `git rev-parse MERGE_HEAD`, not `[ -f .git/MERGE_HEAD ]`: in a worktree `.git`
# is a FILE pointing at the real gitdir, so the path test is always false there
# and a clean merge with no regenerated delta would silently go uncommitted.
if git diff --cached --quiet && ! git rev-parse -q --verify MERGE_HEAD >/dev/null; then
  echo "Nothing to commit — branch already consistent with $BASE."
  exit 0
fi

git commit --no-verify -m "chore(quests): refresh report branch against ${BASE#origin/}

Merge ${BASE#origin/} and rebuild the generated ledger + dashboard + quest-reports
collection so the report PR is mergeable again. Conflicts were confined to
regenerated files; the walkthrough sources (the only authored inputs) are
untouched." >/dev/null

echo "✅ refreshed — $(git rev-parse --short HEAD)"
