version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    
    volumes:
      - ..:/workspace:cached
      - bundle-cache:/usr/local/bundle
    
    # Use the same network as the main docker-compose for seamless integration
    network_mode: host
    
    # Keep container running for VS Code
    command: sleep infinity
    
    environment:
      - JEKYLL_ENV=development
      - BUNDLE_PATH=/usr/local/bundle

volumes:
  bundle-cache:
